### ISSUE TITLE
Nested states and views.

### ISSUE THREAD

**Issue by betz** [Kunstmaan/angular-super-seed#1]
Hi!

First of all, wow! This repo looks amazing.
A lot of new concepts for me, never even heard of the ui-router to be honest.
Looking at the docs at https://github.com/angular-ui/ui-router/wiki/Nested-States-&-Nested-Views I see you could nest states.
Now it seems the angular super seed does it's own funky stuff, which I am not really understanding.

For the states, I see states in config.js in the common/config folder, but the same state in home/config/states.json. What's this about?
And how would it be possible to nest states? Could you give a small example?

Cheers, and thanks for sharing this!
Tom

**Comment by SpoBo** [comment]
Hi Tom!

You're right that our seed does some funky stuff. We provide an easy way to configure the router via config. If you want to create a nested state you should add it in your states.json file in the feature folder that's most logic.

The `config.js` file gets overridden each time the grunt config task is ran. So don't edit that one :p We should perhaps add a disclaimer at the top of the file in comments. The grunt config task simply collects all config.json & states.json files.

An example of a nested state using config:

```
{
   "inbox": {
     "path": "/inbox",
     "controller": "InboxCtrl.js",
     "templateUrl": "inbox.html"
   },
   "inbox.details": {
     "path": "/:emailId",
     "controller": "EmailDetailsCtrl.js",
     "templateUrl": "email_details.html"
   }
}
```

As a sidenote, you can still use UI router manually by just accessing the $stateProvider etc in a config phase. The config is just another option we provide. Using the config makes it really obvious what states there are though. And you can also use the states in your protractor tests which is nice :)

Close this issue whenever it feels clear to you.

**Comment by daanporon** [comment]
Not sure if you attended the meetup where we tried to explain most of this stuff. But there is also a video available online: http://bit.ly/angularmeetup

The config.js is generated when the grunt task is run but there are also watches on the config.json and state.json files so that it is regenerated whenever something changes in the config.json or state.json files. As Vincent already mentioned, you never have to do anything in the config.js file, this one is generated. And is also in the .gitignore file.

**Comment by betz** [comment]
I'll have a look to the video, thanks for putting it online.
I was subscribed to the meetup, but didn't make it in the end. Too bad.
Thanks for explaining this, I sure have much more to learn.

Hope to meet you guys at a next angularjs or nodejs meetup.

Cheers,
Tom

**Comment by SpoBo** [comment]
I'll definitely be going to future AngularJS meetups. See you there @betz !
